#!/usr/bin/env bash
#
# Pull the latest generated OpenAPI spec from the InvoiceShelf app repo.
#
# The spec is generated by `php artisan scramble:export` in the app repo's CI
# (.github/workflows/openapi.yml) and committed to public/openapi.json on the
# 3.x branch. This script copies it into the Docker build context, overwriting
# the committed placeholder.
#
# Run automatically by .github/workflows/build.yml; safe to run locally too.
set -euo pipefail

REPO="${SPEC_REPO:-InvoiceShelf/InvoiceShelf}"
BRANCH="${SPEC_BRANCH:-3.x}"
DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

url="https://raw.githubusercontent.com/${REPO}/${BRANCH}/public/openapi.json"
echo "→ ${BRANCH}: ${url}"
if ! curl -fsSL "$url" -o "${DIR}/openapi.json"; then
  echo "  ! could not fetch spec — keeping existing openapi.json" >&2
fi

echo "Done. Spec in ${DIR}/openapi.json."
